Repository Robok-Engine/Robok-Engine, pull requests merged in 2024-07, with the labels that each got.

#10 Comments added.
  language/src/main/java/robok/dev/compiler/logic/LogicCompiler.java
Labels: feature

#12 Comments Added.
  language/src/main/java/robok/dev/compiler/logic/LogicCompiler.java
Labels: feature

#13 Added support for variable declaration using the 'var' keyword, fix fragments error.
  app/src/main/java/dev/trindade/robokide/ui/base/RobokFragment.kt
  app/src/main/java/dev/trindade/robokide/ui/fragments/editor/EditorFragment.kt
  language/src/main/java/robok/dev/compiler/logic/LogicCompiler.java
  language/src/main/java/robok/lang/variables/VariableObject.java
Labels: feature, fix

#14 Improvement in reading and storing methods.
  language/src/main/java/robok/dev/compiler/logic/LogicCompiler.java
  language/src/main/java/robok/lang/methods/Method.java
Labels: feature

#15 Improved logs, added runtime.
  language/src/main/java/robok/dev/compiler/logic/LogicCompiler.java
Labels: feature

#16 add readme
  README.md
Labels: documentation, feature

#56 Diagnostic
  app/build.gradle.kts
  app/src/main/java/dev/trindadeaquiles/robokide/ui/components/editor/CodeEditorView.java
  language/build.gradle.kts
  language/src/main/java/robok/dev/diagnostic/logic/Java8BaseListener.java
  language/src/main/java/robok/dev/diagnostic/logic/Java8BaseVisitor.java
  language/src/main/java/robok/dev/diagnostic/logic/Java8ErrorListener.java
  language/src/main/java/robok/dev/diagnostic/logic/Java8Lexer.java
  language/src/main/java/robok/dev/diagnostic/logic/Java8Listener.java
  language/src/main/java/robok/dev/diagnostic/logic/Java8Parser.java
  language/src/main/java/robok/dev/diagnostic/logic/Java8Visitor.java
Labels: feature

#66 Diagnostic Handler
  app/src/main/java/dev/trindadeaquiles/robokide/ui/components/editor/RobokCodeEditor.java
  app/src/main/java/dev/trindadeaquiles/robokide/ui/fragments/editor/EditorFragment.kt
  language/src/main/java/robok/dev/diagnostic/logic/DiagnosticHandler.kt
  language/src/main/java/robok/dev/diagnostic/logic/DiagnosticListener.kt
Labels: feature

#71 Some fixes
  app/src/main/java/dev/trindadeaquiles/robokide/ui/fragments/editor/EditorFragment.kt
Labels: fix

#94 Fix build warnings
  .github/workflows/build.yml
  app/build.gradle.kts
  app/src/main/java/com/robok/ide/ui/base/RobokActivity.kt
  app/src/main/java/com/robok/ide/ui/base/RobokFragment.kt
  app/src/main/java/com/robok/ide/utils/Helper.kt
  robok/compiler/build.gradle.kts
  robok/diagnostic/build.gradle.kts
  robok/lang/build.gradle.kts
  robok/util/build.gradle.kts
Labels: fix
