Repository Robok-Engine/Robok-Engine, pull requests merged in 2024-10, with the labels that each got.

#314 feat: make robok-aapt2 independent
  app/src/main/java/org/gampiot/robok/manage/project/ProjectManager.java
  robok/robok-aapt2/build.gradle.kts
  robok/robok-aapt2/src/main/java/org/robok/aapt2/SystemLogPrinter.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/Main.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/Signature.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/io/CentralEnd.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/io/ZioEntry.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/io/ZioEntryInputStream.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/io/ZioEntryOutputStream.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/io/ZipInput.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/apksigner/io/ZipOutput.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/AAPT2Compiler.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/Compiler.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/CompilerTask.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/D8Compiler.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/ECJCompiler.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/exception/CompilerException.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/incremental/IncrementalD8Compiler.java
  robok/robok-aapt2/src/main/java/org/robok/aapt2/compiler/incremental/IncrementalECJCompiler.java
Labels: feature

#323 fix: calling observeViewModel method in configureEditor.
  app/src/main/java/org/robok/engine/ui/activities/editor/EditorActivity.kt
Labels: fix

#325 feat: add contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#333 refactor: Use Compose in Terminal
  app/src/main/java/org/robok/engine/ui/activities/terminal/TerminalActivity.kt
Labels: UI/UX, refactor

#335 refactor: Migrate some files to Kotlin
  app/src/main/java/org/robok/engine/manage/project/ProjectManager.java
  robok/aapt2/src/main/java/org/robok/aapt2/BinaryExecutor.java
  robok/aapt2/src/main/java/org/robok/aapt2/BinaryExecutor.kt
  robok/aapt2/src/main/java/org/robok/aapt2/SystemLogPrinter.java
  robok/aapt2/src/main/java/org/robok/aapt2/SystemLogPrinter.kt
  robok/aapt2/src/main/java/org/robok/aapt2/compiler/CompilerResult.kt
  robok/aapt2/src/main/java/org/robok/aapt2/compiler/exception/AAPT2CompileException.kt
  robok/aapt2/src/main/java/org/robok/aapt2/compiler/exception/CompilerException.kt
  robok/aapt2/src/main/java/org/robok/aapt2/compiler/incremental/file/JavaFile.kt
  robok/aapt2/src/main/java/org/robok/aapt2/logger/LogAdapter.java
  robok/aapt2/src/main/java/org/robok/aapt2/logger/LogAdapter.kt
  robok/aapt2/src/main/java/org/robok/aapt2/logger/Logger.java
  robok/aapt2/src/main/java/org/robok/aapt2/logger/Logger.kt
Labels: refactor

#339 feat: More Arabic Language
  app-strings/src/main/res/values-ar-rSA/strings.xml
Labels: translation

#340 feat. hindi translation
  app-strings/src/main/res/values-hi/strings.xml
Labels: translation

#351 fix: Crash when opening a GUI or other file
  app/src/main/java/org/robok/engine/ui/activities/editor/EditorActivity.kt
  feature/editor/src/main/java/org/robok/engine/feature/editor/RobokCodeEditor.java
Labels: fix
