Repository Robok-Engine/Robok-Engine, pull requests merged in 2024-08, with the labels that each got.

#109 feat: New FilePicker to selectFiles
  app/build.gradle.kts
  app/src/main/java/org/gampiot/robokide/ui/fragments/home/HomeFragment.kt
  feature/feature-res/strings/src/main/res/values/strings.xml
  feature/feature-util/src/main/java/org/gampiot/robokide/feature/util/FileUtil.kt
Labels: feature, UI/UX

#122 feat: new component: PermissionDialog
  .github/workflows/android.yml
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/dialog/PermissionDialog.kt
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/res.kt
  feature/feature-component/src/main/res/drawable/ic_folder_24.xml
  feature/feature-component/src/main/res/drawable/shape_allow_button.xml
  feature/feature-component/src/main/res/drawable/shape_deny_button.xml
  feature/feature-component/src/main/res/drawable/shape_dialog_background.xml
  feature/feature-component/src/main/res/layout/layout_dialog_permission.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
  feature/feature-util/build.gradle.kts
  feature/feature-util/src/main/java/org/gampiot/robok/feature/util/FileUtil.kt
  feature/feature-util/src/main/java/org/gampiot/robok/feature/util/base/RobokActivity.kt
  feature/feature-util/src/main/res/drawable/ic_folder_24.xml
Labels: feature, UI/UX

#121 New Crowdin updates
  feature/feature-res/strings/src/main/res/values-af-rZA/strings.xml
  feature/feature-res/strings/src/main/res/values-ar-rSA/strings.xml
  feature/feature-res/strings/src/main/res/values-ca-rES/strings.xml
  feature/feature-res/strings/src/main/res/values-cs-rCZ/strings.xml
  feature/feature-res/strings/src/main/res/values-da-rDK/strings.xml
  feature/feature-res/strings/src/main/res/values-de-rDE/strings.xml
  feature/feature-res/strings/src/main/res/values-el-rGR/strings.xml
  feature/feature-res/strings/src/main/res/values-en-rUS/strings.xml
  feature/feature-res/strings/src/main/res/values-es-rES/strings.xml
  feature/feature-res/strings/src/main/res/values-fi-rFI/strings.xml
  feature/feature-res/strings/src/main/res/values-fr-rFR/strings.xml
  feature/feature-res/strings/src/main/res/values-hu-rHU/strings.xml
  feature/feature-res/strings/src/main/res/values-it-rIT/strings.xml
  feature/feature-res/strings/src/main/res/values-iw-rIL/strings.xml
  feature/feature-res/strings/src/main/res/values-ja-rJP/strings.xml
  feature/feature-res/strings/src/main/res/values-ko-rKR/strings.xml
  feature/feature-res/strings/src/main/res/values-nl-rNL/strings.xml
  feature/feature-res/strings/src/main/res/values-no-rNO/strings.xml
  feature/feature-res/strings/src/main/res/values-pl-rPL/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rPT/strings.xml
  feature/feature-res/strings/src/main/res/values-ro-rRO/strings.xml
  feature/feature-res/strings/src/main/res/values-ru-rRU/strings.xml
  feature/feature-res/strings/src/main/res/values-sr-rSP/strings.xml
  feature/feature-res/strings/src/main/res/values-sv-rSE/strings.xml
  feature/feature-res/strings/src/main/res/values-tr-rTR/strings.xml
  feature/feature-res/strings/src/main/res/values-uk-rUA/strings.xml
  feature/feature-res/strings/src/main/res/values-vi-rVN/strings.xml
  feature/feature-res/strings/src/main/res/values-zh-rCN/strings.xml
  feature/feature-res/strings/src/main/res/values-zh-rTW/strings.xml
Labels: Crowdin, documentation

#125 New Crowdin updates
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
Labels: translation, Crowdin

#134 feat, refactor: Symbol line in editor, Some refactors on CodeEditor and Some Improvements
  app/build.gradle.kts
  app/src/main/java/org/gampiot/robok/ui/fragments/editor/EditorFragment.kt
  app/src/main/res/layout/fragment_editor.xml
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/editor/RobokCodeEditor.java
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/editor/symbol/RobokSymbolInput.java
  feature/feature-component/src/main/res/layout/layout_code_editor.xml
  feature/feature-res/strings/src/main/java/org/gampiot/robok/feature/res/ResUtils.kt
  feature/feature-setting/build.gradle.kts
  feature/feature-util/src/main/java/org/gampiot/robok/feature/util/base/RobokActivity.kt
Labels: feature

#127 New Crowdin Translations
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
Labels: translation, Crowdin

#137 Github Contribuitors Update
  contributors/TABLE_CONTRIBUTORS_GITHUB.md
  contributors/contributors_github.json
Labels: documentation

#138 Github Contribuitors Update
  contributors/TABLE_CONTRIBUTORS_GITHUB.md
  contributors/contributors_github.json
Labels: documentation

#145 feat, fix: Templates & Some fixes
  .github/workflows/android.yml
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/editor/RobokCodeEditor.java
  feature/feature-component/src/main/res/layout/layout_code_editor.xml
  feature/feature-template/build.gradle.kts
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/project/ProjectTemplatesFragment.java
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/project/adapter/ProjectTemplateAdapter.java
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/project/model/ProjectTemplate.java
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/project/view/ProjectTemplateView.java
  feature/feature-template/src/main/res/drawable/ic_empty_game.png
  feature/feature-template/src/main/res/layout/fragment_project_templates.xml
  feature/feature-template/src/main/res/layout/layout_template_view.xml
Labels: feature, fix

#147 UI Fix: fix CreateProject button overlap, fix EditorFragment RobokSymbolInput not go up with keyboard
  app/src/main/res/layout/fragment_create_project.xml
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/editor/RobokCodeEditor.java
Labels: feature, fix

#148 feat: Diagnostic dotProgress and image system
  app/src/main/java/org/gampiot/robok/ui/fragments/editor/EditorFragment.kt
  app/src/main/res/drawable/ic_error_24.xml
  app/src/main/res/drawable/ic_success_24.xml
  app/src/main/res/layout/fragment_editor.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/editor/EditorListener.kt
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/editor/RobokCodeEditor.java
Labels: feature, WIP

#108 feat: NormalTextField & DialogEditText
  app/build.gradle.kts
  feature/feature-component/build.gradle.kts
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/dialog/DialogEditText.java
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/textfield/NormalTextField.java
  feature/feature-component/src/main/res/layout/layout_dialog_edittext.xml
  feature/feature-component/src/main/res/layout/layout_dialog_input.xml
  feature/feature-setting/build.gradle.kts
  feature/feature-util/build.gradle.kts
Labels: feature, wontfix

#158 feat: EditorFragment toolbar icons align improvements
  app/src/main/res/layout/fragment_editor.xml
Labels: UI/UX

#160 chore: update ANTLR4 to 4.13.2
  feature/feature-component/build.gradle.kts
  robok/robok-diagnostic/build.gradle.kts
  robok/robok-diagnostic/src/main/java/robok/diagnostic/logic/Java8BaseListener.java
  robok/robok-diagnostic/src/main/java/robok/diagnostic/logic/Java8BaseVisitor.java
  robok/robok-diagnostic/src/main/java/robok/diagnostic/logic/Java8Lexer.java
  robok/robok-diagnostic/src/main/java/robok/diagnostic/logic/Java8Listener.java
  robok/robok-diagnostic/src/main/java/robok/diagnostic/logic/Java8Parser.java
  robok/robok-diagnostic/src/main/java/robok/diagnostic/logic/Java8Visitor.java
Labels: feature, dependency

#161 fix: FilePicker file not appear on Android 14
  app/src/main/AndroidManifest.xml
  feature/feature-util/src/main/java/org/gampiot/robok/feature/util/FileUtil.kt
Labels: fix, WIP

#155 feat: Terminal Options
  feature/feature-component/src/main/java/org/gampiot/robok/feature/component/dialog/DialogEditText.java
  feature/feature-res/strings/src/main/res/values/strings.xml
  feature/feature-terminal/build.gradle.kts
  feature/feature-terminal/src/main/java/org/gampiot/robok/feature/terminal/TerminalActivity.java
  feature/feature-terminal/src/main/res/drawable/ic_add_24.xml
  feature/feature-terminal/src/main/res/drawable/ic_back_24.xml
  feature/feature-terminal/src/main/res/drawable/ic_close_24.xml
  feature/feature-terminal/src/main/res/layout/activity_terminal.xml
  feature/feature-terminal/src/main/res/layout/layout_dialog_input.xml
Labels: feature, has-side-effect, WIP

#162 Crowdin Translations Update
  feature/feature-res/strings/src/main/res/values-af-rZA/strings.xml
  feature/feature-res/strings/src/main/res/values-ar-rSA/strings.xml
  feature/feature-res/strings/src/main/res/values-ca-rES/strings.xml
  feature/feature-res/strings/src/main/res/values-cs-rCZ/strings.xml
  feature/feature-res/strings/src/main/res/values-da-rDK/strings.xml
  feature/feature-res/strings/src/main/res/values-de-rDE/strings.xml
  feature/feature-res/strings/src/main/res/values-el-rGR/strings.xml
  feature/feature-res/strings/src/main/res/values-en-rUS/strings.xml
  feature/feature-res/strings/src/main/res/values-es-rES/strings.xml
  feature/feature-res/strings/src/main/res/values-fi-rFI/strings.xml
  feature/feature-res/strings/src/main/res/values-fr-rFR/strings.xml
  feature/feature-res/strings/src/main/res/values-hu-rHU/strings.xml
  feature/feature-res/strings/src/main/res/values-it-rIT/strings.xml
  feature/feature-res/strings/src/main/res/values-iw-rIL/strings.xml
  feature/feature-res/strings/src/main/res/values-ja-rJP/strings.xml
  feature/feature-res/strings/src/main/res/values-ko-rKR/strings.xml
  feature/feature-res/strings/src/main/res/values-nl-rNL/strings.xml
  feature/feature-res/strings/src/main/res/values-no-rNO/strings.xml
  feature/feature-res/strings/src/main/res/values-pl-rPL/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rPT/strings.xml
  feature/feature-res/strings/src/main/res/values-ro-rRO/strings.xml
  feature/feature-res/strings/src/main/res/values-ru-rRU/strings.xml
  feature/feature-res/strings/src/main/res/values-sr-rSP/strings.xml
  feature/feature-res/strings/src/main/res/values-sv-rSE/strings.xml
  feature/feature-res/strings/src/main/res/values-tr-rTR/strings.xml
  feature/feature-res/strings/src/main/res/values-uk-rUA/strings.xml
  feature/feature-res/strings/src/main/res/values-vi-rVN/strings.xml
  feature/feature-res/strings/src/main/res/values-zh-rCN/strings.xml
  feature/feature-res/strings/src/main/res/values-zh-rTW/strings.xml
Labels: translation, Crowdin

#172 feat: Arabic Language, Good App icon
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  feature/feature-res/strings/src/main/res/values-ar-rSA/strings.xml
Labels: feature, translation

#173 feat: add locale-config for android 13+
  app/build.gradle.kts
  app/src/main/java/org/gampiot/robok/ui/activities/MainActivity.kt
  app/src/main/res/resources.properties
  feature/feature-res/strings/src/main/res/xml/locales_config.xml
Labels: feature

#166 feat: complete project system
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/gampiot/robok/ui/fragments/home/HomeFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/project/create/CreateProjectFragment.java
  app/src/main/java/org/gampiot/robok/ui/fragments/project/create/util/ProjectCreator.java
  app/src/main/java/org/gampiot/robok/ui/fragments/project/template/ProjectTemplatesFragment.java
  app/src/main/java/org/gampiot/robok/ui/fragments/project/template/model/ProjectTemplate.java
  app/src/main/res/layout/fragment_home.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
  feature/feature-template/src/main/assets/empty_game.zip
  feature/feature-template/src/main/assets/template.zip
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/code/CodeTemplate.java
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/code/android/game/logic/GameScreenLogicTemplate.java
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/code/java/JavaClassTemplate.java
  feature/feature-template/src/main/java/org/gampiot/robok/feature/template/code/rbk/RBKLayoutTemplate.java
  feature/feature-treeview/.gitignore
  feature/feature-treeview/build.gradle.kts
  feature/feature-treeview/proguard-rules.pro
  feature/feature-treeview/src/main/AndroidManifest.xml
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/file/example/FileNode.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/file/example/FileTreeNodeViewHolder.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/file/example/FileTreeViewActivity.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/holder/SimpleViewHolder.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/model/TreeNode.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/view/AndroidTreeView.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/view/TreeNodeWrapperView.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/view/TwoDScrollView.java
  feature/feature-treeview/src/main/res/drawable/ic_collapse.xml
  feature/feature-treeview/src/main/res/drawable/ic_expand.xml
  feature/feature-treeview/src/main/res/drawable/ic_file.xml
  feature/feature-treeview/src/main/res/drawable/ic_folder.xml
  feature/feature-treeview/src/main/res/drawable/ripple_on_color_surface.xml
  feature/feature-treeview/src/main/res/layout/activity_file_tree_view.xml
  feature/feature-treeview/src/main/res/layout/tree_node_item.xml
  feature/feature-treeview/src/main/res/values/ids.xml
  feature/feature-treeview/src/main/res/values/styles.xml
  settings.gradle.kts
Labels: feature, WIP

#178 feat: Engine themes
  app/src/main/java/org/gampiot/robok/theme/CircleImageView.java
  app/src/main/java/org/gampiot/robok/theme/ColorAdapter.java
  app/src/main/java/org/gampiot/robok/theme/Theme.java
  app/src/main/java/org/gampiot/robok/theme/ThemeChooserDialogBuilder.java
  app/src/main/java/org/gampiot/robok/theme/ThemeEngine.java
  app/src/main/java/org/gampiot/robok/theme/ThemeMode.java
  app/src/main/res/drawable/ic_folder_24.xml
  app/src/main/res/drawable/ic_round_check.xml
  app/src/main/res/layout/layout_color_item.xml
  app/src/main/res/layout/layout_recyclerview.xml
  app/src/main/res/values-night/default_colors.xml
  app/src/main/res/values-night/default_theme_overlays.xml
  app/src/main/res/values-night/defualt_theme.xml
  app/src/main/res/values/color_light_brown.xml
  app/src/main/res/values/color_yellow_dark.xml
  app/src/main/res/values/colors_amber.xml
  app/src/main/res/values/colors_blue.xml
  app/src/main/res/values/colors_blue_dark.xml
  app/src/main/res/values/colors_dark_violet.xml
  app/src/main/res/values/colors_green.xml
  app/src/main/res/values/default_colors.xml
  app/src/main/res/values/default_styles.xml
  app/src/main/res/values/default_theme.xml
  app/src/main/res/values/default_theme_overlays.xml
  app/src/main/res/values/intsandbools.xml
  app/src/main/res/values/theme_amber.xml
  app/src/main/res/values/theme_blue.xml
  app/src/main/res/values/theme_blue_dark.xml
  app/src/main/res/values/theme_dark_violet.xml
  app/src/main/res/values/theme_green.xml
  app/src/main/res/values/theme_light_brown.xml
  app/src/main/res/values/theme_yellow_dark.xml
  app/src/main/res/values/themes_a.xml
  gradle.properties
  settings.gradle.kts
Labels: feature, UI/UX

#177 UI: Redesign About Page
  app/build.gradle.kts
  app/src/main/java/org/gampiot/robok/ui/fragments/about/AboutFragment.kt
  app/src/main/res/drawable/clover.xml
  app/src/main/res/drawable/github.xml
  app/src/main/res/drawable/libs.xml
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/people.xml
  app/src/main/res/drawable/send.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/item_contributor.xml
Labels: UI/UX

#180 fix: use strings.xml instead direct texts
  app/src/main/res/layout/fragment_about.xml
  feature/feature-res/strings/src/main/res/values-ar-rSA/strings.xml
  feature/feature-res/strings/src/main/res/values-en-rUS/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
Labels: fix

#182 feat: AboutLibraries
  app/build.gradle.kts
  build.gradle.kts
Labels: feature, dependency

#186 feat: add some params on LibsBuilder of AboutLibraries
  app/src/main/java/org/gampiot/robok/ui/fragments/about/AboutFragment.kt
Labels: feature, UI/UX

#194 feat: SplashScreen Animation
  app/src/main/res/drawable/roboksp.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature, UI/UX

#197 feat: Apply Custom layouts in preferences
  feature/feature-setting/src/main/res/xml/settings_editor.xml
  feature/feature-setting/src/main/res/xml/settings_top.xml
Labels: feature

#201 feat: French language
  feature/feature-res/strings/src/main/res/values-fr-rFR/strings.xml
Labels: wontfix, translation

#210 refactor: init of refactor settings with compose
  .github/telegram/send_apk.py
  .github/workflows/android.yml
  app/src/main/java/org/gampiot/robok/ui/activities/SettingsActivity.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/about/AboutFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/about/adapter/ContributorAdapter.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/about/model/Contributor.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/home/HomeFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/settings/SettingsFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/settings/base/RobokPreferenceFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/settings/base/RobokSettingsFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/settings/editor/SettingsEditorFragment.kt
  app/src/main/res/layout/fragment_home.xml
  build.gradle.kts
  easy-ui/components/build.gradle.kts
  easy-ui/components/src/main/res/layout/layout_preference.xml
  easy-ui/components/src/main/res/layout/layout_preference_switch.xml
  easy-ui/components/src/main/res/layout/layout_preference_switch_withicon.xml
  easy-ui/components/src/main/res/layout/layout_preference_withicon.xml
  easy-ui/filepicker/build.gradle.kts
  feature-compose/feature-component/.gitignore
  feature-compose/feature-component/README.md
  feature-compose/feature-component/build.gradle.kts
  feature-compose/feature-component/proguard-rules.pro
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/ApplicationScreen.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/Title.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/appbars/TopBar.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/cards/CardBox.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/cards/CardTitle.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/cards/SimpleCard.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/composables/AnimatedComposable.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/dialog/TDialog.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/item/DynamicListItem.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/preferences/PreferenceItem.kt
  settings.gradle.kts
Labels: UI/UX, refactor
