Repository Robok-Engine/Robok-Engine, pull requests merged in 2024-09, with the labels that each got.

#212 refactor: continue SettingsRefactor
  .github/telegram/send_apk.py
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/gampiot/robok/ui/activities/SettingsActivity.kt
  app/src/main/java/org/gampiot/robok/ui/theme/Color.kt
  app/src/main/java/org/gampiot/robok/ui/theme/Theme.kt
  app/src/main/java/org/gampiot/robok/ui/theme/Type.kt
  feature-compose/feature-settings/build.gradle.kts
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/repositories/AppPreferencesRepository.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/screens/LibrariesScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/screens/SettingsScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/viewmodels/AppPreferencesViewModel.kt
  feature-compose/feature-settings/src/main/res/values/strings.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
  feature/feature-util/build.gradle.kts
  feature/feature-util/src/main/java/org/gampiot/robok/feature/util/application/RobokApplication.kt
  feature/feature-util/src/main/java/org/gampiot/robok/feature/util/di/Modules.kt
  settings.gradle.kts
Labels: refactor

#219 feat: Remove old Libraries item from About
  .github/workflows/notify_telegram.yml
  app/src/main/java/org/gampiot/robok/ui/fragments/about/AboutFragment.kt
  app/src/main/res/layout/fragment_about.xml
Labels: feature

#220 feat, refactor: Several Improvements on Code Editor Settings, more compose components.
  feature-compose/feature-component/build.gradle.kts
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/dialog/RobokChoiceDialog.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/dialog/RobokDialog.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/preferences/bunny/PreferenceItem.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/preferences/bunny/PreferenceItemChoice.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/preferences/vegabobo/PreferenceItem.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/radio/IntRadioController.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/screens/LibrariesScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/screens/SettingsScreen.kt
  feature/feature-editor/build.gradle.kts
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/Manager.kt
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/RobokCodeEditor.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/ThemeManager.kt
  feature/feature-res/strings/src/main/res/values-ar-rSA/strings.xml
  feature/feature-res/strings/src/main/res/values-fr-rFR/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
Labels: feature, refactor

#221 feat: Update GitHub Contributors
  .github/contributors/TABLE_CONTRIBUTORS_GITHUB.md
  .github/contributors/contributors_github.json
  .github/contributors/contributors_github_temp.json
Labels: feature, documentation

#228 feat: Several improvements in Auto Complete, Java Language Classes
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/RobokCodeEditor.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaIncrementalAnalyzeManager.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaLanguage.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaQuoteHandler.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaTextTokenizer.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/autocomplete/IdentifierAutoComplete.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/Method.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/State.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/Tokens.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/Variable.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/object/ModifierAccess.java
Labels: feature

#233 feat: EditorCodeEditor TypeFace setting & update SDK to 35
  app/build.gradle.kts
  easy-ui/components/build.gradle.kts
  easy-ui/filepicker/build.gradle.kts
  feature-compose/feature-component/build.gradle.kts
  feature-compose/feature-settings/build.gradle.kts
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/repositories/AppPreferencesRepository.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/screens/editor/SettingsCodeEditorScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/viewmodels/AppPreferencesViewModel.kt
  feature/feature-component/build.gradle.kts
  feature/feature-editor/build.gradle.kts
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/EditorConfigManager.kt
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/RobokCodeEditor.java
  feature/feature-res/strings/build.gradle.kts
  feature/feature-res/strings/src/main/res/values-ar-rSA/strings.xml
  feature/feature-res/strings/src/main/res/values-fr-rFR/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
  feature/feature-template/build.gradle.kts
  feature/feature-terminal/build.gradle.kts
  feature/feature-treeview/build.gradle.kts
  feature/feature-util/build.gradle.kts
  robok/robok-aapt2/build.gradle.kts
  robok/robok-compiler/build.gradle.kts
  robok/robok-diagnostic/build.gradle.kts
  robok/robok-lang/build.gradle.kts
  robok/robok-util/build.gradle.kts
Labels: feature, UI/UX

#230 fix: directory HOME in terminal
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/RobokCodeEditor.java
  feature/feature-terminal/src/main/java/org/gampiot/robok/feature/terminal/TerminalActivity.java
Labels: fix, WIP

#246 feat: Check type code in identifier auto complete
  feature/feature-editor/build.gradle.kts
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/autocomplete/IdentifierAutoComplete.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/store/AndroidClasses.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/store/JavaClasses.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/store/RDKClasses.kt
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/store/models/ClassItem.kt
Labels: feature, WIP

#249 fix: editor gives exception when using double quotes
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaTextTokenizer.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/autocomplete/IdentifierAutoComplete.java
Labels: fix

#250 Feat: detect identifiers in variables
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaIncrementalAnalyzeManager.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaLanguage.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/autocomplete/IdentifierAutoComplete.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/Variable.java
Labels: feature

#254 UI: Redesign Settings
  app/proguard-rules.pro
  feature-compose/feature-component/src/main/java/org/gampiot/robok/feature/compose/edges/EdgeEffectCompat.java
  feature-compose/feature-component/src/main/java/org/gampiot/robok/feature/compose/edges/StretchEdgeEffect.java
  feature-compose/feature-component/src/main/java/org/gampiot/robok/feature/compose/utils/Utilities.java
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/icons/ClickableIcon.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/BottomSpacer.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/DividerColumn.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/ExpandAndShrink.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/NestedScrollStretch.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/PreferenceDivider.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/PreferenceGroup.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/PreferenceLayout.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/PreferenceScaffold.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/PreferenceTemplate.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/ScrollContainers.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/base/TopBar.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/bunny/PreferenceItem.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/bunny/PreferenceItemChoice.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/choice/PreferenceChoice.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/normal/Preference.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/preferences/switch/PreferenceSwitch.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/radio/IntRadioController.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/utils/ModifierUtil.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/SettingsScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/editor/SettingsCodeEditorScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/libraries/LibrariesScreen.kt
Labels: feature, UI/UX

#255 UI: Redesign About
  app/src/main/java/org/gampiot/robok/ui/activities/SettingsActivity.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/about/AboutFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/about/adapter/ContributorAdapter.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/about/model/Contributor.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/home/HomeFragment.kt
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/fragment_home.xml
  feature-compose/feature-settings/build.gradle.kts
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/SettingsScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/about/AboutScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/libraries/LibrariesScreen.kt
  feature-compose/feature-settings/src/main/res/drawable/ic_github_24.xml
  feature-compose/feature-settings/src/main/res/drawable/ic_launcher.png
  feature-compose/feature-settings/src/main/res/drawable/ic_people_24.xml
  feature-compose/feature-settings/src/main/res/drawable/ic_send_24.xml
  feature-compose/feature-settings/src/main/res/drawable/ic_whatsapp_24.xml
  feature-compose/feature-settings/src/main/res/values/attrs.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
Labels: feature, UI/UX

#257 feat: ConfigureRDK Screen
  app/src/main/java/org/gampiot/robok/ui/activities/SettingsActivity.kt
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/textfields/DynamicSelectTextField.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/SettingsScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/rdkmanager/ConfigureRDKScreen.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/utils/ZipDownloader.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/viewmodels/ConfigureRDKViewModel.kt
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/viewmodels/DownloadState.kt
  feature/feature-res/strings/src/main/res/values-ar-rSA/strings.xml
  feature/feature-res/strings/src/main/res/values-fr-rFR/strings.xml
  feature/feature-res/strings/src/main/res/values-pt-rBR/strings.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
  feature/feature-util/src/main/java/org/gampiot/robok/feature/util/di/Modules.kt
Labels: feature, UI/UX

#258 feat: Get releases easily from the Robok-SDK GitHub repo, and add to …
  feature-compose/feature-settings/src/main/kotlin/org/gampiot/robok/feature/settings/compose/ui/screens/rdkmanager/ConfigureRDKScreen.kt
Labels: feature

#260 feat: new FileTree
  app/src/main/java/org/gampiot/robok/app/Res.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/editor/EditorFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/home/HomeFragment.kt
  app/src/main/res/drawable/ic_chevron_24.xml
  app/src/main/res/drawable/ic_expand_24.xml
  app/src/main/res/drawable/ic_file_24.xml
  app/src/main/res/layout/fragment_editor.xml
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/adapters/FileTreeAdapter.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/interfaces/FileClickListener.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/interfaces/FileIconProvider.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/interfaces/FileObject.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/model/TreeViewModel.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/provider/DefaultFileIconProvider.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/provider/File.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/util/Sorter.kt
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/widget/DiagonalScrollView.java
  feature/feature-treeview/src/main/java/org/gampiot/robok/feature/treeview/v2/widget/FileTree.kt
  feature/feature-treeview/src/main/res/drawable/apkfile.xml
  feature/feature-treeview/src/main/res/drawable/archive.xml
  feature/feature-treeview/src/main/res/drawable/bash.xml
  feature/feature-treeview/src/main/res/drawable/contract.xml
  feature/feature-treeview/src/main/res/drawable/file.xml
  feature/feature-treeview/src/main/res/drawable/folder.xml
  feature/feature-treeview/src/main/res/drawable/ic_chevron_right.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_c.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_cpp.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_csharp.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_css.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_html.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_java.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_js.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_json.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_kotlin.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_python.xml
  feature/feature-treeview/src/main/res/drawable/ic_language_xml.xml
  feature/feature-treeview/src/main/res/drawable/image.xml
  feature/feature-treeview/src/main/res/drawable/markdown.xml
  feature/feature-treeview/src/main/res/drawable/music.xml
  feature/feature-treeview/src/main/res/drawable/react.xml
  feature/feature-treeview/src/main/res/drawable/round_expand_more_24.xml
  feature/feature-treeview/src/main/res/drawable/rust.xml
  feature/feature-treeview/src/main/res/drawable/text.xml
  feature/feature-treeview/src/main/res/drawable/video.xml
  feature/feature-treeview/src/main/res/layout/recycler_view_item.xml
Labels: feature

#261 feat: support for predictive gestures.
  app/src/main/AndroidManifest.xml
Labels: feature, UI/UX

#264 chore: remove old filepicker & unused dependencies
  app/build.gradle.kts
  app/src/main/java/org/gampiot/robok/ui/fragments/home/FilePicker.kt
  easy-filepicker/.gitignore
  easy-filepicker/README.md
  easy-filepicker/build.gradle.kts
  easy-filepicker/proguard-rules.pro
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/controller/DialogSelectionListener.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/controller/NotifyItemChecked.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/controller/adapters/FileListAdapter.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/model/DialogConfigs.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/model/DialogProperties.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/model/FileListItem.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/model/MarkedItemList.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/utils/ExtensionFilter.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/utils/Utility.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/view/FilePickerDialog.java
  easy-filepicker/src/main/java/dev/trindadedev/easyui/filepicker/view/FilePickerPreference.java
  easy-filepicker/src/main/res/anim/marked_item_animation.xml
  easy-filepicker/src/main/res/anim/unmarked_item_animation.xml
  easy-filepicker/src/main/res/drawable/filepickerdialog_shape.xml
  easy-filepicker/src/main/res/drawable/ic_directory_parent.xml
  easy-filepicker/src/main/res/drawable/ic_type_file.xml
  easy-filepicker/src/main/res/drawable/ic_type_folder.xml
  easy-filepicker/src/main/res/layout/dialog_file_list.xml
  easy-filepicker/src/main/res/layout/dialog_file_list_item.xml
  easy-filepicker/src/main/res/layout/dialog_footer.xml
  easy-filepicker/src/main/res/layout/dialog_header.xml
  easy-filepicker/src/main/res/layout/dialog_main.xml
  easy-filepicker/src/main/res/values-pt-rBR/strings.xml
  easy-filepicker/src/main/res/values-w820dp/dimens.xml
  easy-filepicker/src/main/res/values/attrs.xml
  easy-filepicker/src/main/res/values/colors.xml
  easy-filepicker/src/main/res/values/dimens.xml
  easy-filepicker/src/main/res/values/strings.xml
  easy-filepicker/src/main/res/values/themes.xml
Labels: dependencies, chore

#285 feat: Migrate to gradle version catalogs (app)
  app/build.gradle.kts
  app/src/main/java/org/gampiot/robok/ui/activities/SettingsActivity.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature, dependencies

#289 feat: Parallax Effect meme
  feature-compose/feature-component/src/main/kotlin/org/gampiot/robok/feature/component/compose/parallax/ParallaxEffect.kt
Labels: feature, UI/UX

#292 fix: Terminal not working
  .gitignore
  feature/feature-terminal/src/main/java/org/gampiot/robok/feature/terminal/TerminalActivity.java
  feature/feature-terminal/src/main/java/org/gampiot/robok/feature/terminal/TerminalActivity.kt
Labels: fix

#293 fix: auto complete does not show variables and methods
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/JavaLanguage.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/autocomplete/IdentifierAutoComplete.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/Method.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/Method.kt
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/MethodOrField.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/MethodOrField.kt
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/models/Variable.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/object/ModifierAccess.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/store/RDKClasses.kt
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/store/RDKFileMapper.java
  feature/feature-editor/src/main/java/org/gampiot/robok/feature/editor/languages/java/store/models/ClassItem.kt
Labels: fix

#296 refactor: Refactor CreateProjectFragment with Jetpack Compose.
  app/src/main/java/org/gampiot/robok/manage/project/ProjectManager.kt
  app/src/main/java/org/gampiot/robok/models/project/ProjectTemplate.kt
  app/src/main/java/org/gampiot/robok/ui/activities/MainActivity.kt
  app/src/main/java/org/gampiot/robok/ui/activities/editor/EditorActivity.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/project/create/CreateProjectFragment.kt
  app/src/main/java/org/gampiot/robok/ui/fragments/project/create/util/ProjectManager.java
  app/src/main/java/org/gampiot/robok/ui/fragments/project/template/ProjectTemplatesFragment.java
  app/src/main/java/org/gampiot/robok/ui/fragments/project/template/adapter/ProjectTemplateAdapter.java
  app/src/main/java/org/gampiot/robok/ui/fragments/project/template/model/ProjectTemplate.java
  app/src/main/java/org/gampiot/robok/ui/fragments/project/template/view/ProjectTemplateView.java
  app/src/main/java/org/gampiot/robok/ui/screens/home/HomeScreen.kt
  app/src/main/java/org/gampiot/robok/ui/screens/project/create/CreateProjectScreen.kt
  app/src/main/java/org/gampiot/robok/ui/screens/project/create/CreateProjectViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_create_project.xml
  app/src/main/res/layout/fragment_project_templates.xml
  app/src/main/res/layout/item_project_template.xml
  app/src/main/res/layout/layout_template_view.xml
  feature/feature-res/strings/src/main/res/values/strings.xml
Labels: UI/UX, refactor

#301 Hindi translation
  feature/feature-res/strings/src/main/res/values-hi/strings.xml
Labels: feature, translation

#307 ui: change unchecked Switch colors
  core-compose/core-components/src/main/kotlin/org/gampiot/robok/core/components/compose/preferences/switch/PreferenceSwitch.kt
Labels: UI/UX

#308 chore: apply DynamicColor on Application instead MainActivity
  app/src/main/java/org/gampiot/robok/ui/activities/MainActivity.kt
  core/core-utils/src/main/java/org/gampiot/robok/core/utils/application/RobokApplication.kt
  core/core-utils/src/main/java/org/gampiot/robok/core/utils/base/RobokActivity.kt
Labels: chore

#309 feat: libgdx to fragment
  app/src/main/java/org/gampiot/robok/ui/activities/MainActivity.kt
  core/core-utils/src/main/java/org/gampiot/robok/core/utils/application/RobokApplication.kt
  feature/feature-modeling/src/main/java/org/gampiot/robok/feature/modeling/fragment/LibGDXFragment.java
  feature/feature-modeling/src/main/java/org/gampiot/robok/feature/modeling/launcher/AndroidLauncher.java
  feature/feature-modeling/src/main/java/org/gampiot/robok/feature/modeling/launcher/AndroidLauncher.kt
Labels: feature
