Repository Robok-Engine/Robok-Engine, pull requests merged in 2024-11, with the labels that each got.

#360 refactor: Kotlin in XMLViewerActivity
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/XMLViewerActivity.java
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/XMLViewerActivity.kt
Labels: refactor

#364 refactor: Remake XMLViewer with Compose
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/XMLViewerActivity.kt
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/XMLViewerActivityOld.kt
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/XMLViewerScreen.kt
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/components/OutlineView.kt
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/viewmodel/XMLViewerViewModel.kt
Labels: UI/UX, refactor

#372 feat: Use NavHost in XMLViewer to future XMLViewerCode screen
  app/src/main/java/org/robok/engine/navigation/XMLViewerNavHost.kt
  app/src/main/java/org/robok/engine/platform/CompositionLocals.kt
  app/src/main/java/org/robok/engine/routes/XMLViewerRoutes.kt
  app/src/main/java/org/robok/engine/ui/activities/MainActivity.kt
  app/src/main/java/org/robok/engine/ui/activities/xmlviewer/XMLViewerActivity.kt
  app/src/main/java/org/robok/engine/ui/screens/xmlviewer/XMLViewerScreen.kt
Labels: feature/improve

#376 fix: autocomplete rdk not working
  feature/editor/src/main/java/org/robok/engine/feature/editor/languages/java/autocomplete/IdentifierAutoComplete.java
  feature/editor/src/main/java/org/robok/engine/feature/editor/languages/java/store/RDKFileMapper.kt
Labels: fix, WIP

#377 fix: antlr is crashing the editor & fix RDkFileMapper not work in android 14
  feature/editor/src/main/java/org/robok/engine/feature/editor/languages/java/JavaLanguage.java
  feature/editor/src/main/java/org/robok/engine/feature/editor/languages/java/autocomplete/IdentifierAutoComplete.java
  feature/editor/src/main/java/org/robok/engine/feature/editor/languages/java/store/RDKFileMapper.kt
Labels: fix
